name: cicd

on:
  workflow_dispatch:

env:
  APP_NAME: sneakfeed-service

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build image
        run: docker build --tag ${{ secrets.GCP_IMAGE_REGISTRY }}/${{ secrets.GCP_IMAGE_NAME }} .

      - name: Push image
        run: docker push ${{ secrets.GCP_IMAGE_REGISTRY }}/${{ secrets.GCP_IMAGE_NAME }}

      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: "${{ secrets.GCP_IMAGE_NAME }}"
          image: "${{ secrets.GCP_IMAGE_REGISTRY }}/${{ secrets.GCP_IMAGE_NAME }}"
          env_vars: |
            ${{ secrets.ACCESS_TOKEN_KEY }}=${{ secrets.ACCESS_TOKEN_VALUE }}
            ${{ secrets.REFRESH_TOKEN_KEY }}=${{ secrets.REFRESH_TOKEN_VALUE }}
            ${{ secrets.IMAGEKIT_PUBLIC_KEY_KEY }}=${{ secrets.IMAGEKIT_PUBLIC_KEY_VALUE }}
            ${{ secrets.IMAGEKIT_PRIVATE_KEY_KEY }}=${{ secrets.IMAGEKIT_PRIVATE_KEY_VALUE }}
            ${{ secrets.IMAGEKIT_ENDPOINT_URL_KEY }}=${{ secrets.IMAGEKIT_ENDPOINT_URL_VALUE }}
            ${{ secrets.MONGODB_USERNAME_KEY }}=${{ secrets.MONGODB_USERNAME_VALUE }}
            ${{ secrets.MONGODB_PASSWORD_KEY }}=${{ secrets.MONGODB_PASSWORD_VALUE }}
            ${{ secrets.DATABASE_NAME_KEY }}=${{ secrets.DATABASE_NAME_VALUE }}
            ${{ secrets.METADATA_SERVICE_URL_KEY }}=${{ secrets.METADATA_SERVICE_URL_VALUE }}
